"""Migración inicial limpia

Revision ID: a9efe3213e09
Revises: 
Create Date: 2025-11-08 15:54:51.605755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9efe3213e09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=True),
    sa.Column('apellido_usuario', sa.String(length=60), nullable=True),
    sa.Column('correo_usuario', sa.String(length=60), nullable=True),
    sa.Column('contrasena_usuario', sa.String(length=255), nullable=False),
    sa.Column('foto_usuario', sa.String(length=255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo_usuario'), 'usuarios', ['correo_usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('noticias',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=60), nullable=True),
    sa.Column('introduccion', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.String(length=2000), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_revisor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_escritor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['usuario_escritor_id'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuario_revisor_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    op.drop_table('comentarios')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('categorias')
    # ### end Alembic commands ###
